# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6fc13ff1e0f2409424e9ccf2330d04f804483657adfc79eb32a49eec3db6c0c537f4c7a68df80dfc6192786ae829fd24b4cc63dcaa34dbf11965be430c117362

test:
  secret_key_base: 0886c2717afef1fdcfe9875e2b5a8c7b74ea1b5257d48055bb735bc9ac2e9d0ca9481db7625b88ae696ca5822f5a867f77719fc876a2b24aa3ec2ba9054d70f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
